"""'new_schema'

Revision ID: 4cab3839f743
Revises: 
Create Date: 2019-09-19 09:33:15.129301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cab3839f743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phoneNo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('image_location', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_type', sa.String(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('from_destination', sa.String(), nullable=True),
    sa.Column('to_destination', sa.String(), nullable=True),
    sa.Column('bus_company', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ownerName', sa.String(), nullable=True),
    sa.Column('busName', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('max_no_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerName'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('Bus_id', sa.String(), nullable=False),
    sa.Column('Routes_id', sa.String(), nullable=False),
    sa.Column('departing_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departing_time', sa.Time(), nullable=True),
    sa.Column('arriving_time', sa.Time(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['Routes_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('Bus_id', 'Routes_id')
    )
    op.create_table('seats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bus_id', sa.String(), nullable=True),
    sa.Column('time_booked', sa.DateTime(), nullable=True),
    sa.Column('holding', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    op.drop_table('schedules')
    op.drop_table('buses')
    op.drop_table('routes')
    op.drop_table('price')
    op.drop_table('owners')
    op.drop_table('customers')
    # ### end Alembic commands ###
